plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.stardevllc'
version = '0.1.0'

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = 'https://repo.stardevllc.com/releases'
    }
}

dependencies {
    compileOnly 'com.stardevllc:StarLib:0.25.0'
}

publishing {
    repositories {
        maven {
            name="stardev"
            url="https://repo.stardevllc.com/releases"
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }

    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    withJavadocJar()
    withSourcesJar()
}

tasks.named("javadoc", Javadoc) {
    options.addBooleanOption('public', true)
    options.addBooleanOption('Xdoclint:none', true)
}

tasks.jar.finalizedBy(javadocJar)
tasks.jar.finalizedBy(sourcesJar)
tasks.build.finalizedBy(publishToMavenLocal)

tasks.withType(PublishToMavenLocal).configureEach {
    dependsOn(javadocJar)
    dependsOn(sourcesJar)
}

tasks.withType(PublishToMavenRepository).configureEach {
    dependsOn(javadocJar)
    dependsOn(sourcesJar)
}
